apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "snapcast-server.fullname" . }}
  labels:
    {{- include "snapcast-server.labels" $ | nindent 4 }}

data:
  snapserver.conf: |
    {{- tpl .Values.configTemplate $ | nindent 4 }}