apiVersion: v1
kind: Service
metadata:
  name: {{ include "snapcast-server.fullname" $ }}
  labels:
    {{- include "snapcast-server.labels" $ | nindent 4 }}
spec:
  type: {{ .Values.service.type }}

  ports:
  {{- range $port := .Values.service.ports }}
    - port: {{ $port.port }}
      targetPort: {{ $port.name }}
      protocol: TCP
      name: {{ $port.name }}
  {{- end }}
  selector:
    {{- include "snapcast-server.selectorLabels" $ | nindent 4 }}